import {
  ShoppingCart,
  ChefHat,
  Wine,
  Ban,
  RotateCcw,
  FileBarChart,
  Wallet,
  Globe,
} from "lucide-react";
import type { TemplateType, ReceiptTemplateFormData } from "./types";

export const TEMPLATE_TYPES: {
  id: TemplateType;
  label: string;
  icon: typeof ShoppingCart;
}[] = [
  { id: "sale", label: "Sale Receipt", icon: ShoppingCart },
  { id: "kitchen", label: "Kitchen Ticket", icon: ChefHat },
  { id: "bar", label: "Bar Ticket", icon: Wine },
  { id: "void", label: "Void Receipt", icon: Ban },
  { id: "refund", label: "Refund Receipt", icon: RotateCcw },
  { id: "end_of_day", label: "End of Day Report", icon: FileBarChart },
  { id: "cash_drawer", label: "Cash Drawer Report", icon: Wallet },
  { id: "online_order", label: "Online Order Ticket", icon: Globe },
];

type FieldKey = keyof Omit<ReceiptTemplateFormData, "header_text" | "footer_text">;

export const TEMPLATE_FIELD_VISIBILITY: Record<TemplateType, Record<FieldKey, boolean>> = {
  sale: {
    show_logo: true,
    show_item_modifiers: true,
    show_tax_breakdown: true,
    show_tip_line: true,
    show_server_name: true,
    show_order_type: true,
    show_barcode: true,
    show_qr_code: true,
    large_item_text: false,
    show_mods_large: false,
    group_by_station: false,
    show_allergy_alert: false,
    show_ready_by_time: false,
  },
  kitchen: {
    show_logo: false,
    show_item_modifiers: true,
    show_tax_breakdown: false,
    show_tip_line: false,
    show_server_name: true,
    show_order_type: true,
    show_barcode: false,
    show_qr_code: false,
    large_item_text: true,
    show_mods_large: true,
    group_by_station: true,
    show_allergy_alert: true,
    show_ready_by_time: true,
  },
  bar: {
    show_logo: false,
    show_item_modifiers: true,
    show_tax_breakdown: false,
    show_tip_line: false,
    show_server_name: true,
    show_order_type: true,
    show_barcode: false,
    show_qr_code: false,
    large_item_text: true,
    show_mods_large: true,
    group_by_station: false,
    show_allergy_alert: true,
    show_ready_by_time: true,
  },
  void: {
    show_logo: true,
    show_item_modifiers: true,
    show_tax_breakdown: true,
    show_tip_line: false,
    show_server_name: true,
    show_order_type: true,
    show_barcode: false,
    show_qr_code: false,
    large_item_text: false,
    show_mods_large: false,
    group_by_station: false,
    show_allergy_alert: false,
    show_ready_by_time: false,
  },
  refund: {
    show_logo: true,
    show_item_modifiers: true,
    show_tax_breakdown: true,
    show_tip_line: false,
    show_server_name: true,
    show_order_type: true,
    show_barcode: false,
    show_qr_code: false,
    large_item_text: false,
    show_mods_large: false,
    group_by_station: false,
    show_allergy_alert: false,
    show_ready_by_time: false,
  },
  end_of_day: {
    show_logo: true,
    show_item_modifiers: false,
    show_tax_breakdown: true,
    show_tip_line: false,
    show_server_name: false,
    show_order_type: false,
    show_barcode: false,
    show_qr_code: false,
    large_item_text: false,
    show_mods_large: false,
    group_by_station: false,
    show_allergy_alert: false,
    show_ready_by_time: false,
  },
  cash_drawer: {
    show_logo: true,
    show_item_modifiers: false,
    show_tax_breakdown: false,
    show_tip_line: false,
    show_server_name: false,
    show_order_type: false,
    show_barcode: false,
    show_qr_code: false,
    large_item_text: false,
    show_mods_large: false,
    group_by_station: false,
    show_allergy_alert: false,
    show_ready_by_time: false,
  },
  online_order: {
    show_logo: true,
    show_item_modifiers: true,
    show_tax_breakdown: true,
    show_tip_line: false,
    show_server_name: false,
    show_order_type: true,
    show_barcode: true,
    show_qr_code: true,
    large_item_text: false,
    show_mods_large: false,
    group_by_station: false,
    show_allergy_alert: false,
    show_ready_by_time: true,
  },
};

export const DEFAULT_TEMPLATE_VALUES: Record<TemplateType, ReceiptTemplateFormData> = {
  sale: {
    show_logo: true,
    header_text: "",
    footer_text: "Thank you for your purchase!",
    show_item_modifiers: true,
    show_tax_breakdown: true,
    show_tip_line: true,
    show_server_name: true,
    show_order_type: true,
    show_barcode: true,
    show_qr_code: false,
    large_item_text: false,
    show_mods_large: false,
    group_by_station: false,
    show_allergy_alert: false,
    show_ready_by_time: false,
  },
  kitchen: {
    show_logo: false,
    header_text: "",
    footer_text: "",
    show_item_modifiers: true,
    show_tax_breakdown: false,
    show_tip_line: false,
    show_server_name: true,
    show_order_type: true,
    show_barcode: false,
    show_qr_code: false,
    large_item_text: true,
    show_mods_large: true,
    group_by_station: true,
    show_allergy_alert: true,
    show_ready_by_time: true,
  },
  bar: {
    show_logo: false,
    header_text: "",
    footer_text: "",
    show_item_modifiers: true,
    show_tax_breakdown: false,
    show_tip_line: false,
    show_server_name: true,
    show_order_type: true,
    show_barcode: false,
    show_qr_code: false,
    large_item_text: true,
    show_mods_large: true,
    group_by_station: false,
    show_allergy_alert: true,
    show_ready_by_time: true,
  },
  void: {
    show_logo: true,
    header_text: "",
    footer_text: "",
    show_item_modifiers: true,
    show_tax_breakdown: true,
    show_tip_line: false,
    show_server_name: true,
    show_order_type: true,
    show_barcode: false,
    show_qr_code: false,
    large_item_text: false,
    show_mods_large: false,
    group_by_station: false,
    show_allergy_alert: false,
    show_ready_by_time: false,
  },
  refund: {
    show_logo: true,
    header_text: "",
    footer_text: "",
    show_item_modifiers: true,
    show_tax_breakdown: true,
    show_tip_line: false,
    show_server_name: true,
    show_order_type: true,
    show_barcode: false,
    show_qr_code: false,
    large_item_text: false,
    show_mods_large: false,
    group_by_station: false,
    show_allergy_alert: false,
    show_ready_by_time: false,
  },
  end_of_day: {
    show_logo: true,
    header_text: "",
    footer_text: "",
    show_item_modifiers: false,
    show_tax_breakdown: true,
    show_tip_line: false,
    show_server_name: false,
    show_order_type: false,
    show_barcode: false,
    show_qr_code: false,
    large_item_text: false,
    show_mods_large: false,
    group_by_station: false,
    show_allergy_alert: false,
    show_ready_by_time: false,
  },
  cash_drawer: {
    show_logo: true,
    header_text: "",
    footer_text: "",
    show_item_modifiers: false,
    show_tax_breakdown: false,
    show_tip_line: false,
    show_server_name: false,
    show_order_type: false,
    show_barcode: false,
    show_qr_code: false,
    large_item_text: false,
    show_mods_large: false,
    group_by_station: false,
    show_allergy_alert: false,
    show_ready_by_time: false,
  },
  online_order: {
    show_logo: true,
    header_text: "",
    footer_text: "Thank you for your order!",
    show_item_modifiers: true,
    show_tax_breakdown: true,
    show_tip_line: false,
    show_server_name: false,
    show_order_type: true,
    show_barcode: true,
    show_qr_code: true,
    large_item_text: false,
    show_mods_large: false,
    group_by_station: false,
    show_allergy_alert: false,
    show_ready_by_time: true,
  },
};
