import { Section } from "./cms-sections";

export const DEFAULT_PAGE_SECTIONS: Record<string, Section[]> = {
  "/": [
    { id: "home-hero", type: "hero", heading: "Run a smarter restaurant.", heading_accent: "Start to finish.", lede: "DEXA is the all-in-one point-of-sale platform built for modern restaurants. From the first order to the last receipt, every part of your operation runs on one trusted system — designed for speed, accuracy, and peace of mind.", buttons: [{ text: "Request a Demo", link: "/contact", style: "primary" }, { text: "See it in action", link: "/demo", style: "secondary" }], main_image: "/dexa-homehero.png", main_image_alt: "A DEXA POS station in a café, taking an order at the counter", floating_title: "Live order processed", floating_text: "$87.64 · Card · Just now", alignment: "left", items: [{ title: "1,200+", description: "Restaurants on DEXA" }, { title: "99.99%", description: "Uptime, last 90 days" }, { title: "24/7", description: "US-based support" }] },
    { id: "home-value", type: "cards", heading: "Everything your restaurant needs, in one place.", subheading: "Why operators choose DEXA", lede: "Stop juggling six tools to run one restaurant. DEXA brings ordering, payments, kitchen, staff, and reporting together — so you can focus on hospitality.", items: [{ icon: "register", title: "Built for full-service", description: "Coursing, split checks, seat-level tracking, and tableside payments. Every detail of full-service hospitality, handled." }, { icon: "checkmark", title: "Reliable, even offline", description: "Wi-Fi drops? DEXA keeps selling. Orders fire to the kitchen, payments settle, the floor never knows there was an issue." }, { icon: "dollar", title: "Transparent pricing", description: "Cash and card prices on every check. No bundled processor markup, no multi-year hardware lock — keep what you earn." }] },
    { id: "home-explore", type: "cards", heading: "Take a closer look.", subheading: "Explore", lede: "Whether you want to see DEXA in action, compare it side-by-side with the platform you have today, or check whether your existing hardware works — start here.", items: [{ image: "/dexa-og.png", image_alt: "DEXA POS interface preview", title: "Live Demo", description: "Walk through the actual DEXA point-of-sale interface. See how orders flow from the front counter to the kitchen, how payments process, and how reporting comes together.", link: "/demo", link_text: "Open the demo" }, { image: "/dexa-cash.png", image_alt: "DEXA cash register display", title: "Features", description: "Every capability DEXA offers, organized into ten clear categories. Ordering, payments, kitchen operations, staff management, reporting, and more.", link: "/features", link_text: "View features" }, { image: "/dexa-cafe.png", image_alt: "DEXA in a café setting", title: "Why DEXA", description: "How DEXA compares to Toast, Square, and Clover — including the questions operators actually ask before they switch.", link: "/why", link_text: "See the comparison" }, { image: "/dexa-hw2.png", image_alt: "DEXA compatible hardware", title: "Hardware", description: "iPad, Android, Castles, Dejavoo, Star Micronics, Landi. Mix and match the gear that fits your floor — no mandatory devices, no multi-year leases.", link: "/hardware", link_text: "See compatible hardware" }] },
    { id: "home-proof", type: "stats", subheading: "Trusted operations", heading: "A platform restaurants run on every day.", lede: "From single-location food trucks to 50-unit groups, DEXA scales with your business.", items: [{ title: "1,284", description: "Active restaurants" }, { title: "$48.2M", description: "Processed today" }, { title: "99.99%", description: "Uptime, 90 days" }, { title: "3.2 min", description: "Avg support response" }] },
    { id: "home-industries", type: "industries", subheading: "Built for your concept", heading: "Whatever you serve, DEXA fits.", lede: "DEXA configures itself for eight different restaurant concepts, with the right defaults already set for your operation.", button_text: "See how each concept runs DEXA", button_link: "/industries" },
    { id: "home-compare", type: "compare", subheading: "Built Different", heading: "No lock-in.", heading_accent: "On purpose.", lede: "No multi-year contracts, no captive hardware, no processor lock-in. Here's how DEXA compares to the platforms most operators evaluate before they switch.", compare_columns: ["Capability", "DEXA", "Toast", "Square", "Clover"], compare_rows: [["Dual pricing", "Built in", "Add-on", "Workaround", "3rd-party"], ["Hardware choice", "Open", "Toast only", "Square only", "Clover only"], ["Payment processor", "Configurable", "Toast Pay", "Square only", "Locked"], ["Offline mode", "Full", "Limited", "Limited", "Locked"], ["Cash audit log", "Automatic", "Manual", "Limited", "Limited"], ["Contract length", "Month-to-month", "2–3 years", "Variable", "Variable"], ["Multi-location", "Unlimited", "Tier-based", "Variable", "Per-device"]] },
    { id: "home-cta", type: "cta", subheading: "Ready when you are", heading: "See DEXA in your restaurant.", body: "Schedule a 30-minute walkthrough. We'll bring DEXA up on the hardware that fits your concept, configure it for your menu, and answer every question your operator is going to ask.", buttons: [{ text: "Request a Demo", link: "/contact", style: "primary" }, { text: "Try the demo", link: "/demo", style: "ghost-light" }] },
  ],

  "/features": [
    { id: "features-hero", type: "hero", subheading: "Features", heading: "Everything you need. Nothing you don't.", lede: "Six features that change how you operate. Ten capabilities, one platform.", alignment: "center" },
    { id: "features-essentials", type: "core_features", heading: "What you'll notice on day one.", subheading: "The essentials", items: [{ image: "/dexa-dp2.png", icon: "dollar", title: "Dual pricing, built in", description: "Cash and card prices on every check, every receipt. No add-ons, no math at the register." }, { image: "/dexa-og2.png", icon: "checkmark", title: "Works offline", description: "Wi-Fi drops? You keep selling. Orders fire to the kitchen, payments settle when back online." }, { image: "/dexa-kds2.png", icon: "basket", title: "Smart kitchen display", description: "Tickets routed by station. Allergens flagged. Aging timers and bulk advance built in." }, { image: "/dexa-cash.png", icon: "grid", title: "Cash integrity", description: "Every drawer action logged with timestamp and PIN. Suspicious patterns flagged automatically." }, { image: "/dexa-analytics3.png", icon: "chart", title: "Real-time analytics", description: "Sales, labor, top items, payment mix — live from any device. Run from the floor." }, { image: "/dexa-hw1.png", icon: "monitor", title: "Hardware freedom", description: "iPad, Android, Castles, Dejavoo, Star Micronics. Run on the gear you already own." }] },
    { id: "features-capabilities", type: "capabilities", heading: "Ten focused areas. One platform.", subheading: "Full capability surface", lede: "Configurable per location, per station, per role.", items: [{ icon: "register", title: "Order Management", description: "The core ordering surface. Configurable per concept — counter, table, bar, or mixed.", tags: ["Coursing", "Split checks", "Modifiers", "Open tabs"] }, { icon: "dollar", title: "Payments & Processing", description: "Configurable processor, dual pricing, tip-at-sale, Apple Pay and Google Pay.", tags: ["Cash discount", "Tip-at-sale", "Apple Pay", "Pre-auth tabs"] }, { icon: "truck", title: "Online Ordering & Delivery", description: "Direct ordering plus integrations with Uber Eats, DoorDash, Grubhub.", tags: ["Website", "Uber Eats", "DoorDash", "Grubhub"] }, { icon: "basket", title: "Kitchen Operations", description: "Per-station kitchen display, allergen detection, and aging timers.", tags: ["KDS", "Allergen flags", "Aging timers", "Routing"] }, { icon: "bag", title: "Menu & Inventory", description: "Visual menu builder, recipe-linked stock, low-stock alerts, scheduled menus.", tags: ["Menu builder", "Auto-deduct", "Stock alerts", "Schedules"] }, { icon: "users", title: "Staff & Scheduling", description: "Role-based access, PIN logins, drag-to-assign scheduling, tip distribution.", tags: ["PIN login", "Roles", "Scheduling", "Tip splits"] }, { icon: "chart", title: "Reporting & Analytics", description: "Live sales, labor cost, top items, menu engineering, daily closeout.", tags: ["Live sales", "Menu engineering", "Closeout", "P&L"] }, { icon: "heart", title: "Loyalty & Marketing", description: "Phone-based loyalty (no app needed), SMS marketing, birthday offers.", tags: ["Phone signup", "Points", "SMS", "Offers"] }, { icon: "grid", title: "Accounting & API", description: "QuickBooks integration, sales tax handling, payroll exports, open API.", tags: ["QuickBooks", "Tax", "Payroll", "API"] }, { icon: "globe", title: "Multi-Location", description: "Central menu, per-location overrides, group reporting, secure tenant isolation.", tags: ["Central menu", "Overrides", "Group P&L", "Permissions"] }] },
    { id: "features-compare", type: "compare_strip", heading: "How does this compare to what we have?", body: "Side-by-side honesty on the differences that matter — dual pricing, processor freedom, contract length, offline reliability.", button_text: "See the comparison", button_link: "/why", items: [{ title: "Dual pricing", description: "DEXA: built in" }, { title: "Hardware", description: "DEXA: open" }, { title: "Processor", description: "DEXA: configurable" }, { title: "Contract", description: "DEXA: month-to-month" }] },
    { id: "features-cta", type: "cta", subheading: "See it live", heading: "Ready to see DEXA in action?", body: "Walk through the full feature set on a 30-minute call. We'll configure it for your menu, your hardware, and your concept.", buttons: [{ text: "Request a Demo", link: "/contact", style: "primary" }, { text: "Try the demo", link: "/demo", style: "ghost-light" }] },
  ],

  "/pricing": [
    { id: "pricing-hero", type: "hero", subheading: "Pricing", heading: "Honest pricing. Real numbers.", heading_accent: "No tricks.", lede: "Build the plan that fits your floor. One POS station, or fifty. Pay only for what you turn on. No multi-year contracts, no hidden hardware leases, no per-transaction commissions on direct orders.", body: "Trusted by <b>1,284 restaurants</b> across 38 states", floating_title: "Typical full-service setup", floating_text: "$167", caption: "No setup fees", footnote: "Configure your exact plan below", alignment: "left", buttons: [{ text: "Calculate your price", link: "#calculator", style: "primary" }, { text: "Request a demo", link: "/contact", style: "secondary" }], items: [{ title: "First POS station", description: "$99", link_text: "1x" }, { title: "POS tablet", description: "$39", link_text: "1x" }, { title: "Kitchen Display", description: "$29", link_text: "1x" }] },
    { id: "pricing-calculator", type: "pricing_calculator", subheading: "Build your plan", heading: "Calculate your monthly cost.", lede: "Move the controls. The total updates live - no email signup, no quote request, just the real price you'd pay.", settings: { anchor: "calculator", calculator: { prices: { firstStation: 99, addlStation: 49, tablet: 39, kds: 29, onlineOrdering: 100, loyalty: 79, delivery: 79, franchise: 399 }, defaults: { stations: 1, tablets: 1, kds: 1, onlineOrdering: false, loyalty: false, delivery: false, franchise: false }, groups: { devicesTitle: "Stations & tablets", devicesHelp: "How many devices on your floor", addonsTitle: "Add-ons", addonsHelp: "Optional - turn on what you need" }, summaryTitle: "Your monthly cost", totalLabel: "Total / month", emptyText: "Add at least one station to start.", ctaText: "Lock this plan in", ctaLink: "/contact", footnote: "No setup fees - Cancel anytime - 30-day notice", savingsTemplate: "Save approx. {amount}/mo vs a comparable Toast setup" } }, items: [
      { title: "POS Stations", description: "$99 first - $49 each additional", link: "stations" },
      { title: "POS Tablets", description: "$39/month each - tableside ordering", link: "tablets" },
      { title: "Kitchen Displays", description: "$29/month each - station routing", link: "kds" },
      { title: "Online Ordering", description: "$100/month - branded ordering page, no commission", link: "onlineOrdering" },
      { title: "Loyalty Program", description: "$79/month - points, rewards, SMS marketing", link: "loyalty" },
      { title: "Delivery App Integration", description: "$79/month - Uber Eats, Grubhub, DoorDash", link: "delivery" },
      { title: "Franchise Package", description: "$399/month - multi-location tools, royalty calcs", link: "franchise" },
    ] },
    { id: "pricing-core", type: "cards", subheading: "Core POS", heading: "Start with what you need today.", lede: "Add stations as your floor grows. Every device runs the same full DEXA platform - no feature tiers, no upsells, no \"you'll need to upgrade for that.\"", items: [
      { icon: "monitor", title: "First POS Station", description: "Your main register. Full DEXA platform - ordering, payments, menu management, reporting, inventory, staff. One price, every feature.", link: "Start here", link_text: "$99/month", tags: ["Unlimited orders & transactions", "Full reporting & analytics", "Menu management & modifiers", "24/7 support included"] },
      { icon: "grid", title: "Additional Station", description: "Every register after the first. Same full platform, half the price. Add as many as your floor needs - bar, counter, takeout window.", link_text: "$49/month each", tags: ["Real-time sync with main station", "Shared menu, staff, & reports", "No feature limits", "Add or remove anytime"] },
      { icon: "register", title: "POS Tablet", description: "Handheld tableside ordering. Servers send tickets straight to the kitchen and run cards at the table. Perfect for full-service and patios.", link_text: "$39/month each", tags: ["Tableside ordering & payments", "Works on iPad or Android", "Auto-fires to Kitchen Display", "Bluetooth printer support"] },
    ] },
    { id: "pricing-included", type: "cards", heading: "Always included, every plan.", lede: "You won't see these as line items. They come standard with every DEXA subscription.", button_text: "No extra cost", items: [
      { title: "24/7 phone & chat support" },
      { title: "Free software updates" },
      { title: "Onboarding & training" },
      { title: "Real-time reporting" },
      { title: "Menu & modifier management" },
      { title: "Staff & shift management" },
      { title: "Inventory tracking" },
      { title: "Offline mode & auto-sync" },
    ] },
    { id: "pricing-addons", type: "cards", subheading: "Add-ons", heading: "Bolt on what your concept actually uses.", lede: "Every add-on is optional and priced a la carte. Turn them on when you're ready, turn them off if your needs change.", items: [
      { icon: "monitor", title: "Kitchen Display (KDS)", description: "Replace paper tickets. Orders fire from the POS to the kitchen with station routing, course timing, and bump-to-done tracking.", link_text: "$29/mo each", tags: ["Operations"] },
      { icon: "globe", title: "Online Ordering", description: "Branded ordering page on your own website. Pickup, delivery, scheduled orders. No per-transaction commission - flat monthly fee only.", link_text: "$100/month", tags: ["Direct revenue"] },
      { icon: "star", title: "Loyalty Program", description: "Points, rewards, birthday offers, and SMS marketing. Customers enroll at the register or online. Lifetime-value reporting built in.", link_text: "$79/month", tags: ["Retention"] },
      { icon: "truck", title: "Delivery App Integration", description: "Uber Eats, Grubhub, and DoorDash orders flow into the same POS and Kitchen Display. One menu to update. One ticket queue to manage.", link_text: "$79/month", tags: ["Third-party"] },
      { icon: "grid", title: "Franchise Package", description: "Centralized menu, pricing, and reporting across every location. Royalty calculations, brand-wide compliance controls, multi-unit dashboards.", link_text: "$399/month", tags: ["Multi-location"] },
      { icon: "checkmark", title: "Something else?", description: "Custom integrations, accounting sync, gift cards, scheduling tools - many integrations are included or partner-priced. Tell us your stack.", link: "/contact", link_text: "Talk to sales" },
    ] },
    { id: "pricing-compare", type: "compare", subheading: "DEXA vs the rest", heading: "How our pricing stacks up.", lede: "The competitor numbers below are what their published rates look like on paper. The real-world story - required hardware, processor lock-in, contract length - is where most of the cost actually lives.", settings: { variant: "pricing", background: "alt" }, footnote: "* Competitor pricing typically excludes mandatory processor markup, hardware financing, and add-on commissions.", button_text: "See the full comparison", button_link: "/why", compare_columns: ["", "DEXA", "Toast", "Square for Restaurants", "Clover"], compare_rows: [
      ["Starting monthly", "$99/mo", "$0-$69/mo*", "$0-$60/mo*", "$50-$100/mo*"],
      ["Contract length", "Month-to-month", "2-year typical", "Month-to-month", "36-month typical"],
      ["Choose your processor", "Yes", "Toast only", "Square only", "Fiserv only"],
      ["Hardware lock-in", "None - bring your own", "Required leases", "Square hardware only", "Clover devices only"],
      ["Online ordering commission", "0% - flat $100/mo", "Up to 3.5% + flat", "Variable", "Per-order fees"],
      ["Offline mode", "Full POS works offline", "Limited", "Payments require connection", "Limited"],
    ], compare_cell_styles: [
      [{}, {}, {}, {}, {}],
      [{}, { tone: "positive", icon: "check" }, { tone: "muted" }, {}, { tone: "muted" }],
      [{}, { tone: "positive", icon: "check" }, { tone: "muted", icon: "x" }, { tone: "muted", icon: "x" }, { tone: "muted", icon: "x" }],
      [{}, { tone: "positive", icon: "check" }, { tone: "muted", icon: "x" }, { tone: "muted" }, { tone: "muted", icon: "x" }],
      [{}, { tone: "positive" }, {}, {}, {}],
      [{}, { tone: "positive", icon: "check" }, { tone: "strong" }, { tone: "muted" }, { tone: "strong" }],
    ] },
    { id: "pricing-testimonials", type: "cards", subheading: "Trusted by operators", heading: "What restaurants pay - and what they say.", lede: "Three operators. Three concepts. Three honest takes on what they actually spend each month.", items: [
      { title: "Casey Walker", description: "We saved $400/month switching from Toast. No more processor markup, no more leases. The dashboard tells me what I actually need to know - covers per server, food cost by item, the bar's busy hour. That's it. No fluff.", link_text: "Owner, Maple & Vine - Pays $245/mo" },
      { title: "Marcus Chen", description: "Three locations, one POS, one bill. Pricing scales with us, not against us. When we opened location three, I added two stations, a tablet, and a KDS in twenty minutes - no contract renegotiation, no rep calls.", link_text: "Founder, Coastal Bowls - 3 locations - Pays $1,184/mo" },
      { title: "Elena Rodriguez", description: "I was scared of switching POS systems mid-service. DEXA's onboarding team had us running in three days with zero downtime. The price is the price. No surprises on the second invoice. That alone was worth it.", link_text: "Owner, Cocina Verde - Pays $128/mo" },
    ] },
    { id: "pricing-trust", type: "stats", items: [
      { title: "1,284", description: "Active restaurants" },
      { title: "$48.2M", description: "Processed daily" },
      { title: "99.99%", description: "Uptime, 90 days" },
      { title: "3.2min", description: "Avg support response" },
    ] },
    { id: "pricing-faq", type: "faq", subheading: "FAQ", heading: "The questions everyone asks.", lede: "Pricing should be the easy part. Here's everything we get asked before someone signs up.", items: [
      { title: "What happens if I add or remove a station mid-month?", description: "<p>Pro-rated, both ways. Add a station on day 15 and you're billed for half a month at $49. Remove one and you get a credit on your next invoice. No conversations with sales required.</p>" },
      { title: "Do I have to use DEXA's payment processor?", description: "<p>No. DEXA is processor-agnostic - keep the one you have, or use ours for competitive flat-rate pricing. The monthly subscription is software only. Unlike Toast or Clover, we don't lock you into a specific payment processor.</p>" },
      { title: "What exactly counts as a \"station\"?", description: "<p>One full POS terminal - typically a countertop register. Tablets used for tableside service are priced separately at $39/mo and don't count as stations. Kitchen Displays are also separate at $29/mo. A \"station\" is specifically a primary checkout point.</p>" },
      { title: "Are there any setup fees or hidden costs?", description: "<p>None. Onboarding, menu setup, hardware configuration, and staff training are all included in your monthly subscription. The only thing we charge for outside the monthly subscription is hardware itself, and only if you buy it from us (you can also bring your own).</p>" },
      { title: "What if I want to cancel?", description: "<p>30 days' notice. No cancellation fees, no contract penalties, no exit charges. We export all your menu, sales history, and customer data so you can take it with you. We'd rather earn your business every month than trap you.</p>" },
      { title: "Do you offer volume discounts?", description: "<p>Yes - for operators running 5+ locations or 10+ stations, enterprise pricing kicks in. The Franchise Package at $399/mo already includes most multi-location tooling. For larger groups, <a href=\"/contact\">talk to us</a> and we'll build a custom quote.</p>" },
      { title: "What's included in 24/7 support?", description: "<p>Phone, chat, and email - answered by a real human in under 4 minutes on average. We don't tier support by plan size. The single-location food truck gets the same priority as the 50-location chain.</p>" },
      { title: "Can I bring my own hardware?", description: "<p>Absolutely. DEXA runs on iPad, Android tablets, and most existing POS hardware (Castles, Dejavoo, Star Micronics, Landi, and more - see our <a href=\"/hardware\">compatibility list</a>). Software pricing is the same whether you bring your own or buy through us.</p>" },
    ] },
    { id: "pricing-cta", type: "cta", subheading: "Ready when you are", heading: "Get a real quote for your restaurant.", body: "Tell us your concept, your floor count, and what you'd want turned on. We'll send back an exact monthly price and walk you through the platform in 30 minutes.", buttons: [{ text: "Request a Demo", link: "/contact", style: "primary" }, { text: "Try the live demo", link: "/demo", style: "ghost-light" }] },
  ],

  "/why": [
    { id: "why-hero", type: "hero", subheading: "Why DEXA", heading: "Built different. On purpose.", lede: "No multi-year contracts, no captive hardware, no processor lock-in. Here's how DEXA stacks up against the platforms most operators evaluate — and the questions they ask before switching.", alignment: "center" },
    { id: "why-trust", type: "stats", heading: "Why DEXA", items: [
      { title: "1,284", description: "Restaurants on DEXA" },
      { title: "99.99%", description: "Uptime, last 90 days" },
      { title: "24/7", description: "US-based support" },
      { title: "0-day", description: "Contract minimum" },
    ] },
    { id: "why-photo", type: "image", heading: "Your hardware. Your processor. Your terms.", src: "/dexa-hero.png", alt: "A DEXA POS terminal running in a working restaurant dining room" },
    { id: "why-compare", type: "compare", subheading: "The comparison", heading: "DEXA vs. the rest.", lede: "An honest side-by-side. Here's how DEXA stacks up against the platforms most operators evaluate.", compare_columns: ["Capability", "DEXA", "Toast", "Square", "Clover"], compare_rows: [
      ["Dual pricing", "Built in", "Add-on", "Workaround", "3rd-party"],
      ["Hardware choice", "Open", "Toast only", "Square only", "Clover only"],
      ["Payment processor", "Configurable", "Toast Pay", "Square only", "Locked"],
      ["Offline mode", "Full", "Limited", "Limited", "Limited"],
      ["Cash audit log", "Automatic", "Manual", "Manual", "Manual"],
      ["Contract length", "Month-to-month", "2–3 yr", "Variable", "Variable"],
      ["Multi-location", "Unlimited", "Tier-based", "Limited", "Per-device"],
    ] },
    { id: "why-diff", type: "cards", heading: "Built different — and here's why it matters.", subheading: "What sets us apart", lede: "The table above is the summary. Here's the substance behind each line — the design decisions that change what your week actually looks like.", items: [
      { icon: "dollar", title: "Dual pricing, built in", description: "Cash and card prices are structural to the platform — not a third-party add-on or a manual workaround. Customers see both prices, and you stop absorbing card fees on every single sale." },
      { icon: "monitor", title: "Open hardware", description: "Run DEXA on the gear that fits your floor. No captive, single-vendor hardware — bring what you already own or choose from a wide range of terminals, tablets, and printers." },
      { icon: "settings", title: "Configurable processor", description: "Keep your processor or move to a better rate. DEXA isn't a payments company taking a slice of every swipe — the software is the product, so your processing stays competitive." },
      { icon: "wifi", title: "Full offline mode", description: "21 core operations keep running when the internet drops — orders, payments, drawers, refunds under manager PIN. The queue syncs in the right order the moment you reconnect." },
      { icon: "shield", title: "Automatic cash audit", description: "Every drawer event is logged with timestamp and PIN. Reconciliation, variance thresholds, and fraud detection are built into the platform — not bolted on after a discrepancy." },
      { icon: "clock", title: "Month-to-month", description: "Software is month-to-month; hardware you own outright. No multi-year lock-in, no early-termination fee, no auto-renewal that needs 90 days' written notice to escape." },
    ] },
    { id: "why-pricing", type: "cta", subheading: "Honest pricing", heading: "Priced to scale. Never to trap.", body: "Start with what you need today and add only what your concept actually uses — kitchen display, online ordering, loyalty, delivery. Transparent monthly pricing, month-to-month, always.", buttons: [{ text: "See full pricing", link: "/pricing", style: "ghost-light" }], items: [
      { title: "$99", description: "/mo", link_text: "First station" },
      { title: "$49", description: "/mo", link_text: "Additional station" },
      { title: "$39", description: "/mo", link_text: "Handheld tablet" },
    ] },
    { id: "why-faq", type: "faq", subheading: "Common questions", heading: "The questions operators ask.", lede: "Honest answers, no marketing spin.", items: [
      { title: "Is DEXA actually cheaper than Toast or Square?", description: "<p>It depends on volume. The DEXA software fee is competitive — but the real savings come from <strong>not paying captive-hardware margin and not paying captive-processor margin.</strong> On $1M+ in card volume per year, the processor difference alone usually pays for the entire DEXA subscription.</p><p>For low-volume single locations, the dollar difference is smaller. For multi-unit operators, it compounds quickly. We're happy to run the math against your actual statements during the demo.</p>" },
      { title: "How long does migration take?", description: "<p>For a single-location restaurant, two weeks. For a 5–10 location group, four to six weeks. Our migration team handles menu rebuild, staff PIN setup, hardware provisioning, and one week of on-site coverage during cutover.</p><p><strong>We don't do \"you're on your own\" migrations.</strong> Every DEXA deployment includes white-glove onboarding because a botched migration costs everyone money.</p>" },
      { title: "What about my existing payment processor?", description: "<p>If your existing processor supports our integrated terminals, keep them. If they don't, we'll introduce you to processors who do — typically at rates 15–30 basis points below what bundled-POS operators pay.</p><p>We have no exclusive arrangement with any processor. <strong>We make our money from software, not from a transaction tax.</strong></p>" },
      { title: "What happens if my internet goes down?", description: "<p>DEXA keeps running. New orders fire to the kitchen. Cash settles. Tables merge. Drawers open. Refunds process under manager PIN. The customer never knows there was an issue.</p><p>When connectivity returns, the queue syncs in the right order. <strong>You won't lose a transaction to a network outage.</strong></p>" },
      { title: "Is there a multi-year contract?", description: "<p>No. Software is month-to-month. Hardware you buy outright. There's no early termination fee, no minimum-volume clause, no automatic renewal that requires 90 days of written notice to escape.</p><p><strong>If we don't earn your business every month, you don't owe us next month.</strong></p>" },
      { title: "When is DEXA NOT the right fit?", description: "<p>Three cases. <strong>One:</strong> very low-volume operations doing under $100K per year — Square's free tier is genuinely cheaper. <strong>Two:</strong> operators who want zero configuration — DEXA gives you per-station tuning, which means somebody has to make decisions during onboarding. <strong>Three:</strong> operators who specifically want a bundled processor at a markup.</p><p>If any of those describe you, we'll tell you on the call. We'd rather lose a sale than lose a customer in month four.</p>" },
      { title: "Who's actually using DEXA today?", description: "<p>Over 1,200 restaurants across the United States. The mix skews toward full-service: coursing-heavy fine dining, multi-unit pizzeria groups, café chains, and bars with complex tab management.</p><p>Largest deployment: 47 locations across two states. <strong>Smallest: a single food truck running offline-first because their commissary's Wi-Fi is unreliable.</strong> We're equally happy with both.</p>" },
      { title: "What kind of support do you offer after launch?", description: "<p>24/7 phone support, US-based. Real humans, no chatbot screening you out before you can speak to someone. Average response time under three minutes for urgent calls during service hours.</p><p>Every account also gets a dedicated onboarding specialist for the first 90 days. <strong>If you have a problem, you have a person.</strong></p>" },
    ] },
    { id: "why-cta", type: "cta", subheading: "Run the math", heading: "Compare against your current platform.", body: "Send us a recent processing statement. We'll come back with a side-by-side cost breakdown — line by line — within one business day.", buttons: [{ text: "Request the comparison", link: "/contact", style: "primary" }, { text: "Try the demo first", link: "/demo", style: "ghost-light" }] },
  ],

  "/hardware": [
    { id: "hw-hero", type: "hero", subheading: "Hardware", heading: "Run on the gear that fits your floor.", lede: "DEXA is hardware-agnostic by design. iPad, Android, Castles, Dejavoo, Star Micronics, Landi — mix and match. No mandatory devices, no multi-year leases.", alignment: "center" },
    { id: "hw-categories", type: "cards", heading: "Four categories. Endless flexibility.", subheading: "What you'll need", items: [
      { image: "/dexa-pos-terminals.png", image_alt: "DEXA POS terminals", title: "POS Terminals", description: "Run DEXA on landscape Android, iPad, or all-in-one terminals. Bring your own gear, or use ours — your data lives in the cloud, not the device.", tags: ["iPad (7th gen+)", "Galaxy Tab A8", "Lenovo M10", "Landi C20Pro"] },
      { image: "/dexa-terminal.png", image_alt: "DEXA payment terminal", title: "Payment Terminals", description: "EMV chip, NFC tap-to-pay, Apple Pay and Google Pay supported. Wi-Fi primary with USB fallback. No processor lock-in.", tags: ["Castles Saturn1000", "Dejavoo P18", "Dejavoo P8", "DVPayLite"] },
      { image: "/dexa-printers.png", image_alt: "DEXA receipt and kitchen printers", title: "Receipt & Kitchen Printers", description: "Wi-Fi auto-discovery, per-station routing, ESC/POS standard. Thermal for the front, impact for the kitchen — both work out of the box.", tags: ["Star TSP100III", "Star SP742", "Generic ESC/POS"] },
      { image: "/dexa-cashdrawer.png", image_alt: "DEXA cash drawer and display hardware", title: "Cash Drawers & Displays", description: "Standard 12V/24V cash drawers. Customer-Facing Display pairs over QR — any spare Android tablet works. Kitchen Display on any 15-22\" screen.", tags: ["APG Vasario", "MMF Heritage", "Any Android CFD", "Any KDS display"] },
    ] },
    { id: "hw-principles", type: "cards", heading: "Three principles that keep your hardware reliable.", subheading: "How it works", items: [
      { icon: "wifi", title: "Auto-discovery", description: "Plug a printer or terminal into your network — DEXA finds it automatically. No driver downloads, no IP configuration, no setup wizards." },
      { icon: "usb", title: "USB fallback", description: "If Wi-Fi drops, USB takes over within milliseconds. Plug, unplug, replug — the system reroutes seamlessly. No configuration needed." },
      { icon: "globe", title: "Cloud sync", description: "Terminals replicate to the cloud over secure connections, but the device is authoritative locally. You'll never lose a transaction to a network outage." },
    ] },
    { id: "hw-compat", type: "cta", heading: "Already own gear? You probably keep most of it.", body: "Send us a list of your current hardware. We'll come back with a compatibility report within one business day. Most operators reuse 60–80% of their existing gear when migrating to DEXA.", button_text: "Check Compatibility", button_link: "/contact", items: [
      { title: "60-80%", description: "Hardware reusable" },
      { title: "0", description: "Multi-year leases" },
      { title: "4+", description: "Terminal vendors" },
      { title: "1day", description: "Compat report" },
    ] },
    { id: "hw-cta", type: "cta", subheading: "See it on real hardware", heading: "The right gear for your concept.", body: "We'll bring the right hardware to your demo — Castles for high-volume, Dejavoo handhelds for tableside, Landi C20Pro for compact setups.", buttons: [{ text: "Request a Demo", link: "/contact", style: "primary" }, { text: "See by industry", link: "/industries", style: "ghost-light" }] },
  ],

  "/industries": [
    { id: "ind-hero", type: "hero", subheading: "Industries", heading: "Built for the way your concept runs.", lede: "DEXA configures itself for eight different restaurant concepts, with the right defaults already set for your operation.", alignment: "center" },
    { id: "ind-grid", type: "cards", items: [
      { image: "https://images.unsplash.com/photo-1568901346375-23c9450c58cd?auto=format&fit=crop&w=900&q=80", image_alt: "Quick-service restaurant counter", title: "Quick-Service", description: "Built for speed. Counter-first ordering, two-tap modifiers, fast-pay integration. Average ticket time under 90 seconds.", tags: ["Counter-first UI", "Speed-of-service tracking", "Drive-thru ready"] },
      { image: "https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?auto=format&fit=crop&w=900&q=80", image_alt: "Fine dining restaurant interior", title: "Fine Dining", description: "Coursing, seat-level tracking, allergen flagging, and tableside payment. The hospitality details that matter at $80 entrée tickets.", tags: ["Coursing", "Seat-level orders", "Wine list integration"] },
      { image: "https://images.unsplash.com/photo-1495474472287-4d71bcdd2085?auto=format&fit=crop&w=900&q=80", image_alt: "Café coffee bar", title: "Cafés & Coffee Shops", description: "Morning rush handled. Recipe-linked inventory tracks beans, milks, and syrups in real time. Loyalty enrollment by phone number.", tags: ["Recipe inventory", "Phone loyalty", "Modifier-heavy menus"] },
      { image: "https://images.unsplash.com/photo-1565299624946-b28f40a0ae38?auto=format&fit=crop&w=900&q=80", image_alt: "Pizzeria pizza", title: "Pizzerias", description: "Half-and-half toppings, by-the-slice pricing, delivery dispatch. Native integrations with Slice, Uber Eats, DoorDash, and Grubhub.", tags: ["Half-and-half", "Slice integration", "Delivery dispatch"] },
      { image: "https://images.unsplash.com/photo-1595257841889-eca2678454e2?auto=format&fit=crop&w=900&q=80", image_alt: "Food truck service window", title: "Food Trucks", description: "LTE-friendly. Fully offline-capable. Mobile printer support, single-tablet operation. Park anywhere, sell anywhere.", tags: ["Offline-first", "LTE optimized", "Single-tablet mode"] },
      { image: "https://images.unsplash.com/photo-1514933651103-005eec06c04b?auto=format&fit=crop&w=900&q=80", image_alt: "Bar and lounge interior", title: "Bars & Lounges", description: "Open tabs with pre-auth, complex split checks, bottle-service tracking. Manager-PIN voids, cash-drawer audit trail.", tags: ["Open tabs", "Pre-auth holds", "Complex splits"] },
      { image: "https://images.unsplash.com/photo-1606787366850-de6330128bfc?auto=format&fit=crop&w=900&q=80", image_alt: "Deli and market counter", title: "Delis & Markets", description: "Weight-based pricing, bulk-item barcodes, mixed retail and prepared food. Tax handling that knows the difference.", tags: ["Scale integration", "Barcode scanner", "Mixed tax rules"] },
      { image: "https://images.unsplash.com/photo-1551218808-94e220e084d2?auto=format&fit=crop&w=900&q=80", image_alt: "Catering spread at an event", title: "Catering & Events", description: "Pre-order workflow, deposit handling, headcount-based pricing. Custom invoicing with line-item breakdowns for corporate accounts.", tags: ["Pre-orders", "Deposits", "Custom invoicing"] },
    ] },
    { id: "ind-multi", type: "cta", subheading: "Multi-Location", heading: "One platform. Every location.", body: "Central menu management, per-location overrides, group reporting, and secure tenant isolation. Scale from one restaurant to fifty without changing tools — or training your managers twice.", button_text: "Talk to our multi-location team", button_link: "/contact", main_image: "/dexa-platform.png", main_image_alt: "DEXA multi-location dashboard", items: [
      { title: "47", description: "Largest deployment" },
      { title: "1", description: "Dashboard for all" },
    ] },
    { id: "ind-cta", type: "cta", subheading: "Built for your concept", heading: "Let's configure it for your operation.", body: "Tell us your concept on the demo call and we'll bring DEXA up pre-configured — with the right defaults, the right hardware, and the right integrations for how you actually run service.", buttons: [{ text: "Request a Demo", link: "/contact", style: "primary" }, { text: "Try the demo", link: "/demo", style: "ghost-light" }] },
  ],

  "/contact": [
    { id: "contact-hero", type: "hero", heading: "Let's see if DEXA is right for you.", lede: "Tell us about your restaurant. We'll come back within one business day with a 30-minute demo configured for how you actually run service.", alignment: "center" },
    { id: "contact-steps", type: "cards", heading: "What happens next.", subheading: "No pressure, no hard sell. Here's our actual process:", items: [{ title: "Day 1 - Discovery call", description: "15 minutes. We learn about your concept, your current pain points, and what you're trying to fix. If DEXA isn't a fit, we'll tell you on this call." }, { title: "Day 2-7 - Tailored demo", description: "30-minute walkthrough on real hardware, with your menu pre-loaded. We answer the operator-level questions and show you the workflows your team will actually use." }, { title: "Day 8-30 - Migration & cutover", description: "If you decide to move forward, our team handles menu rebuild, hardware setup, and one week of on-site coverage during cutover. You're never doing this alone." }] },
    { id: "contact-form", type: "contact_form", heading: "Request your demo", lede: "Takes 60 seconds. We don't share your information.", subheading: "What happens next.", body: "No pressure, no hard sell. Here's our actual process:", button_text: "Request Demo", footnote: "By submitting, you agree to be contacted by our team about scheduling a demo. We don't sell your information or add you to any marketing list without your consent.", success_heading: "Got it. We'll be in touch.", success_body: "Expect a call or email within one business day. If your matter is urgent, you can reach us directly at (555) 555-DEXA.", error_text: "Something went wrong. Please email us directly at sales@dexapos.com.", contact_phone: "Or call us directly: (555) 555-DEXA", contact_email: "Email: sales@dexapos.com", contact_hours: "Hours: Mon-Fri, 8am-8pm ET. Support 24/7", main_image: "/dexa-og2.png", main_image_alt: "A DEXA POS station configured and ready for service", items: [{ title: "Day 1 - Discovery call", description: "15 minutes. We learn about your concept, your current pain points, and what you're trying to fix. If DEXA isn't a fit, we'll tell you on this call." }, { title: "Day 2-7 - Tailored demo", description: "30-minute walkthrough on real hardware, with your menu pre-loaded. We answer the operator-level questions and show you the workflows your team will actually use." }, { title: "Day 8-30 - Migration & cutover", description: "If you decide to move forward, our team handles menu rebuild, hardware setup, and one week of on-site coverage during cutover. You're never doing this alone." }] },
    { id: "contact-cta", type: "cta", heading: "Ready to get started?", body: "Or call us directly: (555) 555-DEXA. Mon–Fri, 8am–8pm ET. Support 24/7.", button_text: "Send us a message", button_link: "#form" },
  ],

  "/demo": [
    { id: "demo-hero", type: "hero", subheading: "Live Demo", heading: "See DEXA. The way your team will.", lede: "This is the actual DEXA point-of-sale interface, running below in your browser. Tap any tile — Sales, Tables, Kitchen Display, Inventory, Analytics — to see real screens with real data.", alignment: "center" },
    { id: "demo-frame", type: "demo_frame", lede: "Tip: try Sales (build an order) → Inventory (see stock levels) → Analytics (revenue by day)" },
    { id: "demo-annotations", type: "annotations", heading: "Three things to notice as you click around.", subheading: "What you're seeing", items: [{ icon: "dollar", title: "Two prices on every item", description: "Open Sales. Each menu card shows the card price in black and the cash price in green. The order totals carry both through to the receipt — built-in, not an add-on." }, { icon: "package", title: "Inventory tied to the menu", description: "Open Inventory. Stock levels update in real time as orders fire. Low-stock and out-of-stock items surface automatically with reorder buttons." }, { icon: "chart", title: "Decisions, not just data", description: "Open Analytics. Daily revenue, top items, payment mix, channel breakdown — the views your operators actually use to run the business, not generic dashboards." }] },
    { id: "demo-cta", type: "cta", subheading: "Want the full walkthrough?", heading: "Better in person.", body: "Schedule a 30-minute live demo. We'll bring DEXA up on real hardware, configure it for your menu, and show you the moments that don't make it into the demo above.", buttons: [{ text: "Request a Demo", link: "/contact", style: "primary" }, { text: "See full features", link: "/features", style: "ghost-light" }] },
  ],
};
